source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-reloader'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sqlite3'
gem 'rake'

group :development do
	gem 'sinatra-rax'
end